DICIONARIO = {
    "我": ("wǒ", "eu"),
    "你": ("nǐ", "você"),
    "要": ("yào", "quero"),
    "点": ("diǎn", "pedir"),
    "吃": ("chī", "comer"),
    "喝": ("hē", "beber"),
    "米饭": ("mǐfàn", "arroz"),
    "面条": ("miàntiáo", "macarrão"),
    "汤": ("tāng", "sopa"),
    "水": ("shuǐ", "água"),
    "茶": ("chá", "chá"),
    "咖啡": ("kāfēi", "café"),
    "谢谢": ("xièxiè", "obrigado"),
    "再见": ("zàijiàn", "adeus"),
    "请": ("qǐng", "por favor"),
    "一杯": ("yì bēi", "um copo"),
    "一份": ("yí fèn", "uma porção"),
    "好吃": ("hǎochī", "delicioso"),
    "牛肉": ("niúròu", "carne de boi"),
    "鸡肉": ("jīròu", "frango"),
    "猪肉": ("zhūròu", "carne de porco"),
    "鱼": ("yú", "peixe"),
    "蔬菜": ("shūcài", "vegetais"),
    "水果": ("shuǐguǒ", "frutas"),
    "冰淇淋": ("bīngqílín", "sorvete"),
    "蛋糕": ("dàngāo", "bolo"),
    "饺子": ("jiǎozi", "dumplings"),
    "包子": ("bāozi", "pão recheado"),
    "啤酒": ("píjiǔ", "cerveja"),
    "红酒": ("hóngjiǔ", "vinho tinto"),
    "白酒": ("báijiǔ", "licor chinês"),
    "可乐": ("kělè", "coca-cola"),
    "果汁": ("guǒzhī", "suco"),
    "辣": ("là", "picante"),
    "甜": ("tián", "doce"),
    "咸": ("xián", "salgado"),
    "酸": ("suān", "azedo"),
    "苦": ("kǔ", "amargo"),
}