
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'HANZI PONTUACAOfrase : frase HANZIfrase : HANZIfrase : frase PONTUACAOfrase : frase HANZI frase'
    
_lr_action_items = {'HANZI':([0,1,2,3,4,5,],[2,3,-2,2,-3,3,]),'$end':([1,2,3,4,5,],[0,-2,-1,-3,-4,]),'PONTUACAO':([1,2,3,4,5,],[4,-2,-1,-3,4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'frase':([0,3,],[1,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> frase","S'",1,None,None,None),
  ('frase -> frase HANZI','frase',2,'p_frase','compilador.py',24),
  ('frase -> HANZI','frase',1,'p_frase_hanzi','compilador.py',28),
  ('frase -> frase PONTUACAO','frase',2,'p_frase_pontuacao','compilador.py',32),
  ('frase -> frase HANZI frase','frase',3,'p_frase_composta','compilador.py',36),
]
