
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'EXPRESSOES PRONOME SUBSTANTIVO VERBOfrase : pronome verbo substantivo\n             | pronome verbo substantivo expressao\n             | expressao pronome verbo substantivo\n             | expressao pronome verbo substantivo expressaopronome : PRONOMEverbo : VERBOsubstantivo : SUBSTANTIVOexpressao : EXPRESSOES'
    
_lr_action_items = {'PRONOME':([0,3,5,],[4,4,-8,]),'EXPRESSOES':([0,9,10,13,],[5,5,-7,5,]),'$end':([1,5,9,10,12,13,14,],[0,-8,-1,-7,-2,-3,-4,]),'VERBO':([2,4,8,],[7,-5,7,]),'SUBSTANTIVO':([6,7,11,],[10,-6,10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'frase':([0,],[1,]),'pronome':([0,3,],[2,8,]),'expressao':([0,9,13,],[3,12,14,]),'verbo':([2,8,],[6,11,]),'substantivo':([6,11,],[9,13,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> frase","S'",1,None,None,None),
  ('frase -> pronome verbo substantivo','frase',3,'p_frase','compilador.py',33),
  ('frase -> pronome verbo substantivo expressao','frase',4,'p_frase','compilador.py',34),
  ('frase -> expressao pronome verbo substantivo','frase',4,'p_frase','compilador.py',35),
  ('frase -> expressao pronome verbo substantivo expressao','frase',5,'p_frase','compilador.py',36),
  ('pronome -> PRONOME','pronome',1,'p_pronome','compilador.py',45),
  ('verbo -> VERBO','verbo',1,'p_verbo','compilador.py',49),
  ('substantivo -> SUBSTANTIVO','substantivo',1,'p_substantivo','compilador.py',53),
  ('expressao -> EXPRESSOES','expressao',1,'p_expressao','compilador.py',57),
]
